Repository wenzhixin/multiple-select, pull requests merged in 2019-04, with the labels that each got.

#408 Allowed placeholder from html
  multiple-select.js
Labels: enhancement

#374 Makes option labels appear clickable
  multiple-select.css
Labels: enhancement

#409 fix #309: Remove selectAll whitespace
  multiple-select.js
Labels: bug

#412 Rewrote src to ES6.
  .eslintignore
  .eslintrc.js
  .gitignore
  README.md
  bower.json
  docs/_i18n/en/getting-started/download.md
  docs/_i18n/zh-cn/getting-started/download.md
  docs/assets/js/template.js
  multiple-select.css
  multiple-select.js
  package.json
  rollup.config.js
  src/multiple-select.js
  src/multiple-select.png
  src/multiple-select.scss
  tools/template.js
Labels: feature
